language: android
jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository

script:
  - "./gradlew -PdisablePreDex build"

notifications:
  slack: malm-dev:rSWGtyhfdbakZfSVGNi182o5
